<?php

/**
 * Helper function for pulling a random first name.
 */
function random_data_first_name() {

  $first_names = array(
    'Sean',
    'Lev',
    'Andrea',
    'Tauno',
    'Brandon',
    'John',
    'Jonathan',
    'Grant',
    'Lee',
    'Steve',
    'Stephen',
    'Chris',
    'Christian',
    'Jill',
    'Julie',
    'Jane',
    'Jack',
    'Jasmine',
    'Sally',
    'Kerry',
    'Susanne',
    'Susan',
    'Linda',
    'LouAnn',
    'Richard',
    'Eric',
    'Erik',
    'Edwin',
    'Edward',
    'Liz',
    'Elizabeth',
    'Anna',
    'Anne',
    'Alan',
    'Alexandra',
    'Alex',
    'Thomas',
    'Tony',
    'Paul',
    'Pauline',
    'Tim',
    'Timothy',
    'Zack',
    'Jed',
    'Kelly',
    'Kyle',
    'Pam',
    'Pat',
    'Patrick',
    'Patricia',
    'Robert',
    'Roberto',
    'Albert',
    'Alberto',
    'Lander',
    'Wolfe',
    'Skip',
    'Miles',
    'Johnny',
    'Stewart',
    'Katherine',
    'Catherine',
    'Annie',
    'Brian',
    'Hans',
    'Janet',
    'T.J.',
    'Kristin',
    'Margaux',
    'Erin',
    'Jeffery',
    'Alyssa',
    'Alisa',
    'Alexis',
    'Bill',
    'Jake',
    'Katie',
    'Jay',
    'Matt',
    'Matthew',
    'Will',
    'Bri',
    'Cindy',
    'Melissa',
    'Adam',
    'Tess',
    'Skip',
    'Sky',
    'Holly',
    'Kris',
    'Nicole',
    'Jason',
    'Dax',
    'Jordan',
    'Heather',
    'Laura',
    'Rob',
    'Drew',
    'Andrew',
    'Grant',
    'Nate',
    'Nathen',
    'Khari',
    'Rich',
    'Fletcher',
    'Mason',
    'Sheena',
    'Turin',
    'Sallie',
    'Elisa',
    'Dorinda',
    'Pace',
    'Sandra',
    'Maria',
    'Myra',
    'Krista',
    'David',
    'Greg',
    'Gregg',
    'Edric',
    'Lisa',
    'Mary Beth',
    'Michelle',
    'Flynn',
    'Heidi',
    'Lauren',
    'Cyrus',
    'Josie',
    'Jan',
    'Julia',
    'Nikki',
    'Cody',
    'Dana',
    'Earl',
    'Emily',
    'Sun',
    'Milo',
    'Blaise',
    'Erica',
    'Jewel',
    'Corey',
    'Walter',
    'Justin',
    'Randall',
    'Chandra',
    'Amanda',
    'Chad',
    'Wilson',
    'Luther',
    'Moira',
    'Damien',
    'Kelly',
    'Shannon',
    'Marlene',
    'Kevin',
    'Richard',
    'Art',
    'Amye',
    'Anthony',
    'Amy',
    'A.J.',
    'Fred',
    'Felipe',
    'Karen',
    'Carl',
    'Karl',
    'Sarah',
    'Sara',
    'Shawn',
    'Mary',
    'Mark',
    'Josh',
    'Peter',
    'Kristina',
    'Christine',
    'Jesse',
    'Becky',
    'Bob',
    'Peggy',
    'Silus',
    'River',
    'Mark',
    'Marcus',
    'Jim',
    'Terry',
    'Lupine',
    'Charles',
    'Betty',
    'Joe',
    'Stacy',
    'Stacey',
    'Stiv',
    'Jamie',
    'Lewis',
    'Carol',
    'Jeremy',
    'Scott',
    'Mike',
    'Phillips',
  );

  return random_data_array_item($first_names);
}

/**
 * Helper function for pulling a random first name.
 */
function random_data_last_name() {

  $last_names = array(
    'French',
    'King',
    'Stockton',
    'Mitchell',
    'Oakland',
    'Jackson',
    'Toledo',
    'White',
    'Bane',
    'Zane',
    'Larkin',
    'Tsypin',
    'Burton',
    'Hogue',
    'Lee',
    'Parker',
    'Taylor',
    'Moore',
    'Stetson',
    'Peterbuilt',
    'Cruise',
    'Jonze',
    'Fey',
    'Patel',
    'Ryan',
    'Doe',
    'Lawson',
    'Dawson',
    'Grant',
    'Cooper',
    'Anderson',
    'Andersen',
    'Bishop',
    'Regan',
    'Hupp',
    'Stevens',
    'Stevenson',
    'Santana',
    'Santiago',
    'Barber',
    'Smith',
    'Davison',
    'O\'Reilly',
    'O\'Neil',
    'Givingsworth',
    'Peters',
    'Peterson',
    'Stratton',
    'Huckley',
    'Earhart',
    'Hudson',
    'Scott',
    'Lemon',
    'Michaels',
    'Angelo',
    'Frost',
    'Turner',
    'Maxwell',
    'Clinton',
    'Wonder',
    'Quinn',
    'Bridges',
    'Madison',
    'Jacob',
    'Simone',
    'Simon',
    'Eustis',
    'Simpson',
    'Eagle',
    'Hoffman',
    'Lichten',
    'Winston',
    'Bowers',
    'Cook',
    'Bethea',
    'Eckberg',
    'Arnold',
    'Bowron',
    'Born',
    'Ingle',
    'Backer',
    'Savage',
    'Robinson',
    'Merlin',
    'Spencer',
    'Byrne',
    'Cahill',
    'Ernst',
    'Hatfield',
    'Boil',
    'Kern',
    'Fish',
    'Lincoln',
    'Nash',
    'Duke',
    'Shipman',
    'Baird',
    'McNaughty',
    'Butcher',
    'Meyers',
    'Heckman',
    'Cort',
    'Woods',
    'Son',
    'Hammer',
    'Goodman',
    'Loveless',
    'Sharp',
    'Tompkins',
    'Lewis',
    'Wild',
    'Griffin',
    'Griggs',
    'Rogers',
    'Roberts',
    'Irvington',
    'Odefey',
    'Michels',
    'Kroman',
    'Evans',
    'Yaggi',
    'Sanderson',
    'Jobs',
    'McQueen',
    'Sanders',
    'Rodrigo',
    'Rodgers',
    'Robertson',
    'Tyler',
  );

  return random_data_array_item($last_names);
}

/**
 * Helper function for pulling random organizations.
 */
function random_data_organization() {
  $organizations = array(
    'Lucky Critters Shelter',
    'Kitten Defense Fund',
    'Rose City Squirrel Shelter',
    'A Horse is a Horse Of Course Adoptions',
    'Oregon Foundation for Animal Shelters',
    'NYC Cares About Pets',
    'Fish Have Feelings Too',
    'Society for the Ethical Treatment of Clams',
    'Crouching Tigers Need a Home',
    'Cat People Care',
    'Bark If You Love Cats',
    'Beautiful Pets',
    'One Fish Two Fish',
    'Pet Supplies Are Us',
  );

  return random_data_array_item($organizations);
}

/**
 * Generate a random state.
 */
function random_data_state() {
  $states = array(
    'OR',
    'WA',
    'ID',
    'CA',
    'MA',
  );

  return random_data_array_item($states);
}

/**
 * Generate a random city.
 */
function random_data_city() {
  $cities = array(
    'Missoula',
    'Portland',
    'Vancouver',
    'Los Angeles',
    'Boseman',
    'Boise',
  );

  return random_data_array_item($cities);
}

/**
 * Generate a random postal code.
 */
function random_data_postal_code() {
  $postal_code = (string) rand(11111, 99999);
  return $postal_code;
}

/**
 * Generate a random street.
 */
function random_data_street() {
  $number = (string) rand(111, 99999);

  $names = array(
    'Pinehurst',
    'Laurelwood',
    'Broadway',
    'Washington',
    'Lincoln',
    'MLK',
    'Burnside',
    'Stark',
  );
  $name = random_data_array_item($names);

  $suffixes = array(
    'Blvd',
    'St',
    'Ave',
  );
  $suffix = random_data_array_item($suffixes);

  $street = $number . ' ' . $name . ' ' . $suffix;
  return $street;
}

/**
 * Generate a random second line of a street.
 */
function random_data_street2() {
  $names = array(
    'Apt',
    'Suite',
    '',
  );
  $name = random_data_array_item($names);

  if ($name) {
    $number = (string) rand(1, 999);
  }

  $street2 = $name . ' ' . $number;
  return $street2;
}

/**
 * Generate a random campaign name.
 */
function random_data_campaign_name() {
  $nouns = array(
    'deer',
    'lions',
    'tigers',
    'mice',
    'doggies',
    'kittens',
    'bears',
    'tarantulas',
    'squids',
  );
  $animals1 = ucwords(random_data_array_item($nouns));
  $animals2 = ucwords(random_data_array_item($nouns));

  $adjectives = array(
    'for',
    'against',
    'in support of',
    'behind',
    'despite',
    'supporting',
  );
  $adjective = random_data_array_item($adjectives);

  return $animals1 . ' ' . $adjective . ' ' . $animals2;
}

/**
 * Generate a random team name.
 */
function random_data_campaign_team_name() {
  $names = array(
    'magical stuff',
    'spider lord',
    'fan tastic',
    'mousedom',
    'awesome',
    'rock',
    'squirrel',
    'jay',
    'fred',
    'john',
    'mary',
    'kate',
    'engage',
    'trek',
    'fundog',
    'smartwise',
    'gamgee',
    'shire',
  );
  return 'Team ' . random_data_array_item($names) . ' ' . random_data_array_item($names);
}

/**
 * Return a random element of an array.
 *
 * @param array $items
 *   Array of items.
 *
 * @return array|stdClass|string
 *   One item of the array.
 */
function random_data_array_item(array $items) {
  if (count($items >= 1)) {
    $delta = array_rand($items, 1);
    $item = $items[$delta];
  }
  else {
    $item = NULL;
  }
  return $item;
}
